In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("cricketODI.csv")

C:\Users\Kavya sree\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (1,2,3,6,7,8,9,17,18,20,21,22,26,27) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
print(df)

            Innings Player Innings Runs Scored Innings Runs Scored Num  \
0                   JJ Roy                 180                     180
1                 AD Hales                 171                     171
2                 RA Smith                167*                     167
3                   JJ Roy                 162                     162
4                 DI Gower                 158                     158
...                    ...                 ...                     ...
171963  Samiullah Shinwari                 NaN                     NaN
171964       Asghar Afghan                 NaN                     NaN
171965   Najibullah Zadran                 NaN                     NaN
171966         Rahmat Shah                 NaN                     NaN
171967       Ikram Alikhil                 NaN                     NaN

       Innings Minutes Batted  Innings Batted Flag  Innings Not Out Flag  \
0                         151                  1.0                   0.0
1                         166                  1.0                   0.0
2                         208                  1.0                   1.0
3                         172                  1.0                   0.0
4                         177                  1.0                   0.0
...                       ...                  ...                   ...
171963                    NaN                  NaN                   NaN
171964                    NaN                  NaN                   NaN
171965                    NaN                  NaN                   NaN
171966                    NaN                  NaN                   NaN
171967                    NaN                  NaN                   NaN

       Innings Balls Faced Innings Boundary Fours Innings Boundary Sixes  \
0                      151                     16                      5
1                      122                     22                      4
2                      163                     17                      3
3                      118                     13                      3
4                      118                     18                      4
...                    ...                    ...                    ...
171963                 NaN                    NaN                    NaN
171964                 NaN                    NaN                    NaN
171965                 NaN                    NaN                    NaN
171966                 NaN                    NaN                    NaN
171967                 NaN                    NaN                    NaN

       Innings Batting Strike Rate  ... Innings Overs Bowled  \
0                           119.20  ...                  NaN
1                           140.16  ...                  NaN
2                           102.45  ...                  NaN
3                           137.28  ...                  NaN
4                           133.89  ...                  NaN
...                            ...  ...                  ...
171963                         NaN  ...                  DNB
171964                         NaN  ...                  DNB
171965                         NaN  ...                  DNB
171966                         NaN  ...                  DNB
171967                         NaN  ...                  DNB

       Innings Bowled Flag Innings Maidens Bowled Innings Runs Conceded  \
0                      NaN                    NaN                   NaN
1                      NaN                    NaN                   NaN
2                      NaN                    NaN                   NaN
3                      NaN                    NaN                   NaN
4                      NaN                    NaN                   NaN
...                    ...                    ...                   ...
171963                 0.0                      -                     -
171964                 0.0                      -                     -
171965                 0.0                      -                     -
171966                 0.0                      -                     -
171967                 0.0                      -                     -

       Innings Wickets Taken  4 Wickets  5 Wickets 10 Wickets  \
0                        NaN        NaN        NaN        NaN
1                        NaN        NaN        NaN        NaN
2                        NaN        NaN        NaN        NaN
3                        NaN        NaN        NaN        NaN
4                        NaN        NaN        NaN        NaN
...                      ...        ...        ...        ...
171963                     -        1.0        0.0        0.0
171964                     -        1.0        0.0        0.0
171965                     -        1.0        0.0        0.0
171966                     -        1.0        0.0        0.0
171967                     -        1.0        0.0        0.0

       Innings Wickets Taken Buckets  Innings Economy Rate
0                                NaN                   NaN
1                                NaN                   NaN
2                                NaN                   NaN
3                                NaN                   NaN
4                                NaN                   NaN
...                              ...                   ...
171963                             -                     -
171964                             -                     -
171965                             -                     -
171966                             -                     -
171967                             -                     -

[171968 rows x 28 columns]

In [4]:
d={'Innings Player':'Player Name',
   'Innings Runs Scored':'Runs Scored',
   'Innings Runs Scored Num':'Runs Scored Num',
   'Innings Batted Flag':'Batted Flag',
   'Innings Not Out Flag':'Not Out Flag',
   'Innings Balls Faced':'Balls Faced',
   'Innings Boundary Fours':'Fours',
   'Innings Boundary Sixes':'Sixes',
   'Innings Batting Strike Rate':'Batting Strike Rate',
   "50's":'Half Century',
   "100's":'Century',
   'Innings Runs Scored Buckets':'Runs Scored Buckets',
   'Innings Overs Bowled':'Overs Bowled',
   'Innings Bowled Flag':'Bowled Flag',
   'Innings Maidens Bowled':'Maidens Bowled',
   'Innings Runs Conceded':'Runs Conceded',
   'Innings Wickets Taken':'Wickets Taken',
   'Innings Wickets Taken Buckets':'Wickets Taken Buckets',
   'Innings Economy Rate':'Economy Rate'}

In [5]:
df.rename(columns=d,inplace=True)

In [6]:
print(df)

               Player Name Runs Scored Runs Scored Num Innings Minutes Batted  \
0                   JJ Roy         180             180                    151
1                 AD Hales         171             171                    166
2                 RA Smith        167*             167                    208
3                   JJ Roy         162             162                    172
4                 DI Gower         158             158                    177
...                    ...         ...             ...                    ...
171963  Samiullah Shinwari         NaN             NaN                    NaN
171964       Asghar Afghan         NaN             NaN                    NaN
171965   Najibullah Zadran         NaN             NaN                    NaN
171966         Rahmat Shah         NaN             NaN                    NaN
171967       Ikram Alikhil         NaN             NaN                    NaN

        Batted Flag  Not Out Flag Balls Faced Fours Sixes Batting Strike Rate  \
0               1.0           0.0         151    16     5              119.20
1               1.0           0.0         122    22     4              140.16
2               1.0           1.0         163    17     3              102.45
3               1.0           0.0         118    13     3              137.28
4               1.0           0.0         118    18     4              133.89
...             ...           ...         ...   ...   ...                 ...
171963          NaN           NaN         NaN   NaN   NaN                 NaN
171964          NaN           NaN         NaN   NaN   NaN                 NaN
171965          NaN           NaN         NaN   NaN   NaN                 NaN
171966          NaN           NaN         NaN   NaN   NaN                 NaN
171967          NaN           NaN         NaN   NaN   NaN                 NaN

        ... Overs Bowled Bowled Flag Maidens Bowled Runs Conceded  \
0       ...          NaN         NaN            NaN           NaN
1       ...          NaN         NaN            NaN           NaN
2       ...          NaN         NaN            NaN           NaN
3       ...          NaN         NaN            NaN           NaN
4       ...          NaN         NaN            NaN           NaN
...     ...          ...         ...            ...           ...
171963  ...          DNB         0.0              -             -
171964  ...          DNB         0.0              -             -
171965  ...          DNB         0.0              -             -
171966  ...          DNB         0.0              -             -
171967  ...          DNB         0.0              -             -

       Wickets Taken  4 Wickets  5 Wickets 10 Wickets Wickets Taken Buckets  \
0                NaN        NaN        NaN        NaN                   NaN
1                NaN        NaN        NaN        NaN                   NaN
2                NaN        NaN        NaN        NaN                   NaN
3                NaN        NaN        NaN        NaN                   NaN
4                NaN        NaN        NaN        NaN                   NaN
...              ...        ...        ...        ...                   ...
171963             -        1.0        0.0        0.0                     -
171964             -        1.0        0.0        0.0                     -
171965             -        1.0        0.0        0.0                     -
171966             -        1.0        0.0        0.0                     -
171967             -        1.0        0.0        0.0                     -

        Economy Rate
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
...              ...
171963             -
171964             -
171965             -
171966             -
171967             -

[171968 rows x 28 columns]

In [7]:
df=df.drop(['Innings Minutes Batted','4 Wickets','5 Wickets','10 Wickets'],axis=1)

In [8]:
print(df)

               Player Name Runs Scored Runs Scored Num  Batted Flag  \
0                   JJ Roy         180             180          1.0
1                 AD Hales         171             171          1.0
2                 RA Smith        167*             167          1.0
3                   JJ Roy         162             162          1.0
4                 DI Gower         158             158          1.0
...                    ...         ...             ...          ...
171963  Samiullah Shinwari         NaN             NaN          NaN
171964       Asghar Afghan         NaN             NaN          NaN
171965   Najibullah Zadran         NaN             NaN          NaN
171966         Rahmat Shah         NaN             NaN          NaN
171967       Ikram Alikhil         NaN             NaN          NaN

        Not Out Flag Balls Faced Fours Sixes Batting Strike Rate  \
0                0.0         151    16     5              119.20
1                0.0         122    22     4              140.16
2                1.0         163    17     3              102.45
3                0.0         118    13     3              137.28
4                0.0         118    18     4              133.89
...              ...         ...   ...   ...                 ...
171963           NaN         NaN   NaN   NaN                 NaN
171964           NaN         NaN   NaN   NaN                 NaN
171965           NaN         NaN   NaN   NaN                 NaN
171966           NaN         NaN   NaN   NaN                 NaN
171967           NaN         NaN   NaN   NaN                 NaN

       Innings Number  ... Half Century Century Runs Scored Buckets  \
0                   2  ...          0.0     1.0             150-199
1                   1  ...          0.0     1.0             150-199
2                   1  ...          0.0     1.0             150-199
3                   2  ...          0.0     1.0             150-199
4                   1  ...          0.0     1.0             150-199
...               ...  ...          ...     ...                 ...
171963              1  ...          NaN     NaN                 NaN
171964              1  ...          NaN     NaN                 NaN
171965              1  ...          NaN     NaN                 NaN
171966              1  ...          NaN     NaN                 NaN
171967              1  ...          NaN     NaN                 NaN

       Overs Bowled  Bowled Flag  Maidens Bowled Runs Conceded Wickets Taken  \
0               NaN          NaN             NaN           NaN           NaN
1               NaN          NaN             NaN           NaN           NaN
2               NaN          NaN             NaN           NaN           NaN
3               NaN          NaN             NaN           NaN           NaN
4               NaN          NaN             NaN           NaN           NaN
...             ...          ...             ...           ...           ...
171963          DNB          0.0               -             -             -
171964          DNB          0.0               -             -             -
171965          DNB          0.0               -             -             -
171966          DNB          0.0               -             -             -
171967          DNB          0.0               -             -             -

        Wickets Taken Buckets Economy Rate
0                         NaN          NaN
1                         NaN          NaN
2                         NaN          NaN
3                         NaN          NaN
4                         NaN          NaN
...                       ...          ...
171963                      -            -
171964                      -            -
171965                      -            -
171966                      -            -
171967                      -            -

[171968 rows x 24 columns]

In [9]:
df=df.fillna(0)

In [10]:
print(df)

               Player Name Runs Scored Runs Scored Num  Batted Flag  \
0                   JJ Roy         180             180          1.0
1                 AD Hales         171             171          1.0
2                 RA Smith        167*             167          1.0
3                   JJ Roy         162             162          1.0
4                 DI Gower         158             158          1.0
...                    ...         ...             ...          ...
171963  Samiullah Shinwari           0               0          0.0
171964       Asghar Afghan           0               0          0.0
171965   Najibullah Zadran           0               0          0.0
171966         Rahmat Shah           0               0          0.0
171967       Ikram Alikhil           0               0          0.0

        Not Out Flag Balls Faced Fours Sixes Batting Strike Rate  \
0                0.0         151    16     5              119.20
1                0.0         122    22     4              140.16
2                1.0         163    17     3              102.45
3                0.0         118    13     3              137.28
4                0.0         118    18     4              133.89
...              ...         ...   ...   ...                 ...
171963           0.0           0     0     0                   0
171964           0.0           0     0     0                   0
171965           0.0           0     0     0                   0
171966           0.0           0     0     0                   0
171967           0.0           0     0     0                   0

       Innings Number  ... Half Century Century Runs Scored Buckets  \
0                   2  ...          0.0     1.0             150-199
1                   1  ...          0.0     1.0             150-199
2                   1  ...          0.0     1.0             150-199
3                   2  ...          0.0     1.0             150-199
4                   1  ...          0.0     1.0             150-199
...               ...  ...          ...     ...                 ...
171963              1  ...          0.0     0.0                   0
171964              1  ...          0.0     0.0                   0
171965              1  ...          0.0     0.0                   0
171966              1  ...          0.0     0.0                   0
171967              1  ...          0.0     0.0                   0

       Overs Bowled  Bowled Flag  Maidens Bowled Runs Conceded Wickets Taken  \
0                 0          0.0               0             0             0
1                 0          0.0               0             0             0
2                 0          0.0               0             0             0
3                 0          0.0               0             0             0
4                 0          0.0               0             0             0
...             ...          ...             ...           ...           ...
171963          DNB          0.0               -             -             -
171964          DNB          0.0               -             -             -
171965          DNB          0.0               -             -             -
171966          DNB          0.0               -             -             -
171967          DNB          0.0               -             -             -

        Wickets Taken Buckets Economy Rate
0                           0            0
1                           0            0
2                           0            0
3                           0            0
4                           0            0
...                       ...          ...
171963                      -            -
171964                      -            -
171965                      -            -
171966                      -            -
171967                      -            -

[171968 rows x 24 columns]

In [11]:
df.sort_values('Player Name',inplace=True)

In [12]:
print(df)

              Player Name Runs Scored Runs Scored Num  Batted Flag  \
84316         A Balbirnie           0               0          1.0
83637         A Balbirnie          12              12          1.0
83672         A Balbirnie          11              11          1.0
83676         A Balbirnie          11              11          1.0
83748         A Balbirnie           9               9          1.0
...                   ...         ...             ...          ...
148667  Zulqarnain Haider           0               0          0.0
58096   Zulqarnain Haider          11              11          1.0
148657  Zulqarnain Haider           0               0          0.0
57824   Zulqarnain Haider         12*              12          1.0
148672  Zulqarnain Haider           0               0          0.0

        Not Out Flag Balls Faced Fours Sixes Batting Strike Rate  \
84316            0.0           9     0     0                0.00
83637            0.0          24     0     1               50.00
83672            0.0          23     0     0               47.82
83676            0.0          34     0     0               32.35
83748            0.0           9     2     0                 100
...              ...         ...   ...   ...                 ...
148667           0.0           0     0     0                   0
58096            0.0           9     2     0              122.22
148657           0.0           0     0     0                   0
57824            1.0          29     0     0               41.37
148672           0.0           0     0     0                   0

       Innings Number  ... Half Century Century Runs Scored Buckets  \
84316               2  ...          0.0     0.0                0-49
83637               1  ...          0.0     0.0                0-49
83672               2  ...          0.0     0.0                0-49
83676               1  ...          0.0     0.0                0-49
83748               2  ...          0.0     0.0                0-49
...               ...  ...          ...     ...                 ...
148667              1  ...          0.0     0.0                   0
58096               2  ...          0.0     0.0                0-49
148657              2  ...          0.0     0.0                   0
57824               1  ...          0.0     0.0                0-49
148672              1  ...          0.0     0.0                   0

       Overs Bowled  Bowled Flag  Maidens Bowled Runs Conceded Wickets Taken  \
84316             0          0.0               0             0             0
83637             0          0.0               0             0             0
83672             0          0.0               0             0             0
83676             0          0.0               0             0             0
83748             0          0.0               0             0             0
...             ...          ...             ...           ...           ...
148667          DNB          0.0               -             -             -
58096             0          0.0               0             0             0
148657          DNB          0.0               -             -             -
57824             0          0.0               0             0             0
148672          DNB          0.0               -             -             -

        Wickets Taken Buckets Economy Rate
84316                       0            0
83637                       0            0
83672                       0            0
83676                       0            0
83748                       0            0
...                       ...          ...
148667                      -            -
58096                       0            0
148657                      -            -
57824                       0            0
148672                      -            -

[171968 rows x 24 columns]

In [13]:
df.drop_duplicates(keep=False,inplace=True)

In [125]:
print(df)

              Player Name Runs Scored Runs Scored Num  Batted Flag  \
84316         A Balbirnie           0               0          1.0
83637         A Balbirnie          12              12          1.0
83672         A Balbirnie          11              11          1.0
83676         A Balbirnie          11              11          1.0
83748         A Balbirnie           9               9          1.0
...                   ...         ...             ...          ...
148667  Zulqarnain Haider           0               0          0.0
58096   Zulqarnain Haider          11              11          1.0
148657  Zulqarnain Haider           0               0          0.0
57824   Zulqarnain Haider         12*              12          1.0
148672  Zulqarnain Haider           0               0          0.0

        Not Out Flag Balls Faced Fours Sixes Batting Strike Rate  \
84316            0.0           9     0     0                0.00
83637            0.0          24     0     1               50.00
83672            0.0          23     0     0               47.82
83676            0.0          34     0     0               32.35
83748            0.0           9     2     0                 100
...              ...         ...   ...   ...                 ...
148667           0.0           0     0     0                   0
58096            0.0           9     2     0              122.22
148657           0.0           0     0     0                   0
57824            1.0          29     0     0               41.37
148672           0.0           0     0     0                   0

       Innings Number  ... Half Century Century Runs Scored Buckets  \
84316               2  ...          0.0     0.0                0-49
83637               1  ...          0.0     0.0                0-49
83672               2  ...          0.0     0.0                0-49
83676               1  ...          0.0     0.0                0-49
83748               2  ...          0.0     0.0                0-49
...               ...  ...          ...     ...                 ...
148667              1  ...          0.0     0.0                   0
58096               2  ...          0.0     0.0                0-49
148657              2  ...          0.0     0.0                   0
57824               1  ...          0.0     0.0                0-49
148672              1  ...          0.0     0.0                   0

       Overs Bowled  Bowled Flag  Maidens Bowled Runs Conceded Wickets Taken  \
84316             0          0.0               0             0             0
83637             0          0.0               0             0             0
83672             0          0.0               0             0             0
83676             0          0.0               0             0             0
83748             0          0.0               0             0             0
...             ...          ...             ...           ...           ...
148667          DNB          0.0               -             -             -
58096             0          0.0               0             0             0
148657          DNB          0.0               -             -             -
57824             0          0.0               0             0             0
148672          DNB          0.0               -             -             -

        Wickets Taken Buckets Economy Rate
84316                       0            0
83637                       0            0
83672                       0            0
83676                       0            0
83748                       0            0
...                       ...          ...
148667                      -            -
58096                       0            0
148657                      -            -
57824                       0            0
148672                      -            -

[171440 rows x 24 columns]

In [14]:
df.head(400)

,Player Name,Runs Scored,Runs Scored Num,Batted Flag,Not Out Flag,Balls Faced,Fours,Sixes,Batting Strike Rate,Innings Number,...,Half Century,Century,Runs Scored Buckets,Overs Bowled,Bowled Flag,Maidens Bowled,Runs Conceded,Wickets Taken,Wickets Taken Buckets,Economy Rate
84316,A Balbirnie,0,0,1.0,0.0,9,0,0,0.00,2,...,0.0,0.0,0-49,0,0.0,0,0,0,0,0
83637,A Balbirnie,12,12,1.0,0.0,24,0,1,50.00,1,...,0.0,0.0,0-49,0,0.0,0,0,0,0,0
83672,A Balbirnie,11,11,1.0,0.0,23,0,0,47.82,2,...,0.0,0.0,0-49,0,0.0,0,0,0,0,0
83676,A Balbirnie,11,11,1.0,0.0,34,0,0,32.35,1,...,0.0,0.0,0-49,0,0.0,0,0,0,0,0
83748,A Balbirnie,9,9,1.0,0.0,9,2,0,100,2,...,0.0,0.0,0-49,0,0.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89814,A Flintoff,0,0,0.0,0.0,0,0,0,0,2,...,0.0,0.0,0,9.0,1.0,0,43,0,0-4,4.77
92263,A Flintoff,0,0,0.0,0.0,0,0,0,0,-,...,0.0,0.0,0,TDNB,0.0,-,-,-,-,-
89807,A Flintoff,0,0,0.0,0.0,0,0,0,0,1,...,0.0,0.0,0,7.0,1.0,1,43,0,0-4,6.14
86621,A Flintoff,0,0,0.0,0.0,0,0,0,0,2,...,0.0,0.0,0,5.0,1.0,0,21,2,0-4,4.20
86613,A Flintoff,0,0,0.0,0.0,0,0,0,0,1,...,0.0,0.0,0,9.0,1.0,1,20,2,0-4,2.22

In [127]:
print(df)

              Player Name Runs Scored Runs Scored Num  Batted Flag  \
84316         A Balbirnie           0               0          1.0
83637         A Balbirnie          12              12          1.0
83672         A Balbirnie          11              11          1.0
83676         A Balbirnie          11              11          1.0
83748         A Balbirnie           9               9          1.0
...                   ...         ...             ...          ...
148667  Zulqarnain Haider           0               0          0.0
58096   Zulqarnain Haider          11              11          1.0
148657  Zulqarnain Haider           0               0          0.0
57824   Zulqarnain Haider         12*              12          1.0
148672  Zulqarnain Haider           0               0          0.0

        Not Out Flag Balls Faced Fours Sixes Batting Strike Rate  \
84316            0.0           9     0     0                0.00
83637            0.0          24     0     1               50.00
83672            0.0          23     0     0               47.82
83676            0.0          34     0     0               32.35
83748            0.0           9     2     0                 100
...              ...         ...   ...   ...                 ...
148667           0.0           0     0     0                   0
58096            0.0           9     2     0              122.22
148657           0.0           0     0     0                   0
57824            1.0          29     0     0               41.37
148672           0.0           0     0     0                   0

       Innings Number  ... Half Century Century Runs Scored Buckets  \
84316               2  ...          0.0     0.0                0-49
83637               1  ...          0.0     0.0                0-49
83672               2  ...          0.0     0.0                0-49
83676               1  ...          0.0     0.0                0-49
83748               2  ...          0.0     0.0                0-49
...               ...  ...          ...     ...                 ...
148667              1  ...          0.0     0.0                   0
58096               2  ...          0.0     0.0                0-49
148657              2  ...          0.0     0.0                   0
57824               1  ...          0.0     0.0                0-49
148672              1  ...          0.0     0.0                   0

       Overs Bowled  Bowled Flag  Maidens Bowled Runs Conceded Wickets Taken  \
84316             0          0.0               0             0             0
83637             0          0.0               0             0             0
83672             0          0.0               0             0             0
83676             0          0.0               0             0             0
83748             0          0.0               0             0             0
...             ...          ...             ...           ...           ...
148667          DNB          0.0               -             -             -
58096             0          0.0               0             0             0
148657          DNB          0.0               -             -             -
57824             0          0.0               0             0             0
148672          DNB          0.0               -             -             -

        Wickets Taken Buckets Economy Rate
84316                       0            0
83637                       0            0
83672                       0            0
83676                       0            0
83748                       0            0
...                       ...          ...
148667                      -            -
58096                       0            0
148657                      -            -
57824                       0            0
148672                      -            -

[171440 rows x 24 columns]

In [128]:
df.to_csv("criket.csv")